[package]
name = "everbyte/rojo-template"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"

[dependencies]
# Dependencies in ReplicatedStorage


[server-dependencies]
# Server dependencies. Only Avaible on Server


[dev-dependencies]
# Test / Dev dependencies. In Testservice 

