name: Publish to Roblox

on: release

jobs:
  publish:
    name: Publsh Project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          check-latest: true

      - name: Install dependencies
        run: yarn

      - uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Report Rojo tool versions
        run: rojo --version

      - name: Report Roblox-TS version
        run: yarn rbxtsc --version

      - name: Build Roblox-TS
        run: yarn run build

      - name: Build Roblox File
        run: yarn run build-rojo
      
      - uses: actions/upload-artifact@v3
        with:
          path: build.rbxl
          if-no-files-found: error

      - name: Upload Roblox File to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build.rbxl
          asset_name: build.rbxl
          tag: ${{ github.ref }}
          overwrite: true

      - name: Deploy to Roblox
        run: rojo upload --cookie "$ROBLOSECURITY" --asset_id $ASSETID
        env:
          ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}
          ASSETID: 123456789
