name: Publish-Project

on: release

jobs:
  publish:
    name: Publsh Project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with: 
        lfs: 'true'
        submodules: 'recursive'

    - uses: Roblox/setup-foreman@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Report tool versions
      run: rojo --version

    - name: Install dependencies
      run: wally install

    - name: Run Test
      run: rojo build --output build.rbxl

    - uses: actions/upload-artifact@v3
      with:
        path: build.rbxl
        if-no-files-found: error

    - name: Upload Roblox File to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build.rbxl
        asset_name: build.rbxl
        tag: ${{ github.ref }}
        overwrite: true

    - name: Deploy to Roblox
      run: rojo upload --cookie "$ROBLOSECURITY" --asset_id $ASSETID
      env:
        ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}
        ASSETID: 9006663690
