name: Code Quality

on:
  pull_request:
    branches: [main]

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          check-latest: true
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Run ESLint
        run: yarn run eslinter

  compiling-test:
    name: Compiling Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          check-latest: true

      - name: Install dependencies
        run: yarn

      - uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Report Rojo tool versions
        run: rojo --version

      - name: Report Roblox-TS version
        run: yarn rbxtsc --version

      - name: Build Roblox-TS
        run: yarn run build

      - name: Build Roblox File
        run: yarn run build-rojo

      - uses: actions/upload-artifact@v3
        if: ${{ !env.ACT }}
        with:
          path: build.rbxl
          if-no-files-found: error
